@startuml zCart

skinparam component {
  componentStyle rectangle
  backgroundColor<<hardware>> Materia
}

node "Single Board Computer - Raspberry Pi 4" {
    [Cart Service] -left- SQLite3
    [Product Recognizer] -up- [Cart Service] : " HTTP/REST"
    [User App] -right- [Cart Service] : HTTP/REST + WebSockets
    database SQLite3 {
        folder Products
        folder Cart
    }
}

[Camera] <<hardware>>
[Load Cell] <<hardware>>
[HX711 Integrated Circuit] <<hardware>>
[Touch Screen LCD Display] <<hardware>>
[Coral Edge TPU] <<hardware>>

[Product Recognizer] -down- [Camera]
[Product Recognizer] -down- [HX711 Integrated Circuit]
[Product Recognizer] -down- [Coral Edge TPU]
[HX711 Integrated Circuit] -down- [Load Cell]
[User App] -left- [Touch Screen LCD Display]

@enduml
