name: Check if should compile TCC
on: 
  push:
    branches:
      - master

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v27
        with:
          path: "./docs/tcc"

      - name: Compile document
        uses: ./.github/workflows/compile_tcc
        if: steps.changed-files.outputs.any_changed
