name: Check Cart Service
on: 
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      should_run_ci: ${{ contains(steps.changed-files.outputs.all_changed_files, 'cart_service') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v27

  run_ci:
    needs: check
    if: ${{ needs.check.outputs.should_run_ci == 'true' }}
    uses: ./.github/workflows/cart_service_ci.yaml
