name: Conditionally compile TCC document
on: 
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      should_compile: ${{ contains(steps.changed-files.outputs.all_changed_files, 'docs/tcc') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v27

  compile:
    needs: check
    if: ${{ needs.check.outputs.should_compile == 'true' }}
    uses: ./.github/workflows/compile_tcc.yaml
