name: Check if should compile TCC
on: 
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v27

  compile:
    uses: ./.github/workflows/compile_tcc.yaml
    if: contains(steps.changed-files.outputs.all_changed_files, 'docs/tcc')
